### ISSUE TITLE
when players get into nether by portal in oneblock world,my server stops

### ISSUE THREAD

**Issue by Rothes** [BentoBoxWorld/AOneBlock#115]
#### Describe the bug
when players get into nether by portal in oneblock world,my server stops

#### Steps to reproduce the behavior
1.Start the server
2.Let a player get into portal
3.Wait a second to enter the nether
4.Your server stopped and the player is kicked because Internal server error

#### Expected behavior
The player should enter the nether, or just do nothing

##### Output of `/bbox version` (Mandatory)
```
[12:33:22] [Server thread/INFO]: Bentobox version：1.14.2
[12:33:22] [Server thread/INFO]: database：JSON
[12:33:22] [Server thread/INFO]: Loaded world：
[12:33:22] [Server thread/INFO]: oneblock_world (OneBlock): &world, nether, end
[12:33:22] [Server thread/INFO]: Loaded addons：
[12:33:22] [Server thread/INFO]: AOneBlock 1.4.0 (ENABLED)
[12:33:22] [Server thread/INFO]: Border 1.0.9 (DISABLED)
[12:33:22] [Server thread/INFO]: Challenges 0.8.3 (ENABLED)
[12:33:22] [Server thread/INFO]: Chat 1.0.5 (ENABLED)
[12:33:22] [Server thread/INFO]: ControlPanel 1.7.0 (ENABLED)
[12:33:22] [Server thread/INFO]: IslandFly 1.8.0 (ENABLED)
[12:33:22] [Server thread/INFO]: Level 2.4.0 (ENABLED)
[12:33:22] [Server thread/INFO]: Likes 2.0.0 (ENABLED)
[12:33:22] [Server thread/INFO]: Limits 1.14.0 (ENABLED)
[12:33:22] [Server thread/INFO]: Warps 1.10.0 (ENABLED)
```

#### Plugins (Optional)
```
Plugins (13): LuckPerms, SignEdit, PlugMan, CS-CoreLib, Vault, Slimefun, BentoBox, Essentials, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, EssentialsSpawn, Multiverse-Core
```
 
### Additional context (Optional)
```
[18:01:44] [Server thread/WARN]: Failed to handle packet for /XXX.X.XX.211:3177
net.minecraft.server.v1_16_R2.ReportedException: Ticking player
at net.minecraft.server.v1_16_R2.EntityPlayer.playerTick(EntityPlayer.java:525) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:143) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:223) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:130) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1126) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
at net.minecraft.server.v1_16_R2.EntityPlayer.b(EntityPlayer.java:799) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.Entity.doPortalTick(Entity.java:1988) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.Entity.entityBaseTick(Entity.java:386) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityLiving.entityBaseTick(EntityLiving.java:261) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.Entity.tick(Entity.java:361) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2337) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityHuman.tick(EntityHuman.java:153) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityPlayer.playerTick(EntityPlayer.java:443) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
... 9 more
[18:01:44] [Server thread/INFO]: Rothes lost connection: Internal server error
[18:01:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_16_R2.ReportedException: Ticking player
at net.minecraft.server.v1_16_R2.EntityPlayer.playerTick(EntityPlayer.java:525) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.PlayerList.disconnect(PlayerList.java:420) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1411) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.NetworkManager.handleDisconnection(NetworkManager.java:321) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:150) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1126) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
at net.minecraft.server.v1_16_R2.EntityPlayer.b(EntityPlayer.java:799) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.Entity.doPortalTick(Entity.java:1988) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.Entity.entityBaseTick(Entity.java:386) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityLiving.entityBaseTick(EntityLiving.java:261) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.Entity.tick(Entity.java:361) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2337) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityHuman.tick(EntityHuman.java:153) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityPlayer.playerTick(EntityPlayer.java:443) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
... 10 more
[18:01:44] [Server thread/ERROR]: Cause of unexpected exception was
java.lang.NullPointerException: null
at net.minecraft.server.v1_16_R2.EntityPlayer.b(EntityPlayer.java:799) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.Entity.doPortalTick(Entity.java:1988) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.Entity.entityBaseTick(Entity.java:386) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityLiving.entityBaseTick(EntityLiving.java:261) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.Entity.tick(Entity.java:361) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2337) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityHuman.tick(EntityHuman.java:153) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.EntityPlayer.playerTick(EntityPlayer.java:443) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.PlayerList.disconnect(PlayerList.java:420) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1411) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.NetworkManager.handleDisconnection(NetworkManager.java:321) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:150) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1126) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[18:01:44] [Server thread/ERROR]: This crash report has been saved to: D:\One\.\crash-reports\crash-2020-08-15_18.01.44-server.txt
[18:01:44] [Server thread/INFO]: Stopping server
[18:01:44] [Server thread/INFO]: [EssentialsAntiBuild] Disabling EssentialsAntiBuild v2.18.0.0
[18:01:44] [Server thread/INFO]: [EssentialsChat] Disabling EssentialsChat v2.18.0.0
[18:01:44] [Server thread/INFO]: [EssentialsSpawn] Disabling EssentialsSpawn v2.18.0.0
[18:01:44] [Server thread/INFO]: [EssentialsProtect] Disabling EssentialsProtect v2.18.0.0
[18:01:44] [Server thread/INFO]: [Essentials] Disabling Essentials v2.18.0.0
[18:01:44] [Server thread/INFO]: [Vault] [Economy] Essentials Economy unhooked.
[18:01:44] [Server thread/ERROR]: There's a good chance you're reloading your server right now. If that's the case, why do you hate yourself? Expect no support from the EssentialsX team when using /reload.
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling BentoBox v1.14.2
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling addons...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling AOneBlock...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling Level...
[18:01:44] [Server thread/INFO]: [BentoBox] [Level] Stopping Level queue
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling Challenges...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling Chat...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling ControlPanel...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling ExtraMobs...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling IslandFly...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling Likes...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling Limits...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling VoidPortals...
[18:01:44] [Server thread/INFO]: [BentoBox] Disabling Warps...
[18:01:44] [Server thread/INFO]: [BentoBox] Addons successfully disabled.
[18:01:44] [Server thread/INFO]: [Vault] Disabling Vault v1.7.3-b131
[18:01:44] [Server thread/INFO]: [Slimefun] Disabling Slimefun vDEV - 630 (git 8b02c18b)
[18:01:44] [Server thread/INFO]: [Slimefun] Backed up Slimefun data to: 2020-08-15-18-01.zip
[18:01:44] [Server thread/INFO]: [CS-CoreLib] Disabling CS-CoreLib vDEV - 90 (git 9dd4a1cf)
[18:01:44] [Server thread/INFO]: [SignEdit] Disabling SignEdit v1.12.2
[18:01:44] [Server thread/INFO]: [PlugMan] Disabling PlugMan v2.1.7
[18:01:44] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.1.93
[18:01:44] [Server thread/INFO]: [LuckPerms] Starting shutdown process...
[18:01:45] [Server thread/INFO]: [LuckPerms] Closing storage...
[18:01:45] [Server thread/INFO]: [LuckPerms] Goodbye!
[18:01:45] [Server thread/INFO]: Saving players
[18:01:45] [Server thread/INFO]: Saving worlds
[18:01:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:eek:verworld
[18:01:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[18:01:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[18:01:49] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:01:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[18:01:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:01:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[oneblock_world]'/minecraft:eek:neblock_world
[18:01:51] [Server thread/INFO]: ThreadedAnvilChunkStorage (oneblock_world): All chunks are saved
[18:01:51] [Server thread/INFO]: Saving chunks for level 'ServerLevel[oneblock_world_nether]'/minecraft:eek:neblock_world_nether
[18:01:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:01:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[18:01:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:01:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:01:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (oneblock_world): All chunks are saved
[18:01:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
>请按任意键继续. . .
```

**Comment by tastybento** [comment]
Looks like a server error. Keep updating the build of 1.16.2 and hopefully they'll fix the bug.

**Comment by Rothes** [comment]
> Looks like a server error. Keep updating the build of 1.16.2 and hopefully they'll fix the bug.

Yes. version git-Spigot-379750e-e354566 (MC: 1.16.2) have fixed it.thanks!!
