### ISSUE TITLE
Server error on /ob visit

### ISSUE THREAD

**Issue by hetile1** [BentoBoxWorld/AOneBlock#169]
#### Describe the bug
New installation of AoneBlock (BentoBox was already in use for skyblock).
When running /ob visit in game, it return an internal server error, from the console you can see the error:

```[11:12:33 INFO]: hetile issued server command: /ob visit configure
[11:12:33 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'ob visit configure' in world.bentobox.aoneblock.commands.PlayerCommand(ob)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.5.jar:git-Paper-675]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2176) ~[patched_1.16.5.jar:git-Paper-675]        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1991) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1944) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1392) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[patched_1.16.5.jar:git-Paper-675]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-675]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.util.Map world.bentobox.bentobox.database.objects.Island.getMetaData()'
        at world.bentobox.visit.managers.VisitAddonManager.getIslandEarnings(VisitAddonManager.java:120) ~[?:?]
        at world.bentobox.visit.panels.player.ConfigurePanel.createValueButton(ConfigurePanel.java:92) ~[?:?]
        at world.bentobox.visit.panels.player.ConfigurePanel.build(ConfigurePanel.java:70) ~[?:?]
        at world.bentobox.visit.panels.player.ConfigurePanel.openPanel(ConfigurePanel.java:230) ~[?:?]
        at world.bentobox.visit.commands.player.VisitConfigureCommand.execute(VisitConfigureCommand.java:100) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-675]
        ... 18 more
```

#### Steps to reproduce the behavior
1- Go to the island
2- Type /ob visit help

#### Expected behavior
Not exactly sure, this never worked, but I assume it should TP me to an island once I give him a name

##### Output of `/bbox version` (Mandatory)

```
[11:20:07 INFO]: Running PAPER 1.16.5.
[11:20:07 INFO]: BentoBox version: 1.16.2
[11:20:07 INFO]: Database: JSON
[11:20:07 INFO]: Loaded Game Worlds:
[11:20:07 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[11:20:07 INFO]: oneblock_world (OneBlock): Overworld, Nether*
[11:20:07 INFO]: Loaded Addons:
[11:20:07 INFO]: AOneBlock 1.5.5 (ENABLED)
[11:20:07 INFO]: Biomes 1.14.0 (ENABLED)
[11:20:07 INFO]: BSkyBlock 1.14.4 (ENABLED)
[11:20:07 INFO]: Challenges 0.8.4 (ENABLED)
[11:20:07 INFO]: ControlPanel 1.13.0 (ENABLED)
[11:20:07 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[11:20:07 INFO]: Level 2.6.2 (ENABLED)
[11:20:07 INFO]: Limits 1.15.5 (ENABLED)
[11:20:07 INFO]: Visit 1.1.0 (ENABLED)
[11:20:07 INFO]: Warps 1.10.2 (ENABLED)```

#### Plugins (Optional)
```
[11:20:43 INFO]: Plugins (34): BentoBox, ChatColor2, Citizens, CleanroomGenerator, ConsoleSpamFix, DeadChest, DiscordSRV, dynmap*, Essentials, GlowAPI*, HolographicDisplays, HoloMobHealth, HotReloadWhitelist*, LoneLibs, LuckPerms, McDuels, MCLink*, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NameColorGUI, PacketListenerApi*, ProtocolLib, ServerBooster, SetHome*, SignShop, SinglePlayerSleep, TabTPS, Vault, VeinMiner, ViaBackwards, ViaVersion, WorldEdit, WorldGuard```
 

Here is a full boot log of the server:
https://pastebin.com/raw/ig3yGPAH

**Comment by BONNe** [comment]
You are using an outdated Visit addon version.

1.1.0 is not compatible with 1.16.2

You either need to upgrade the Visit addon or downgrade the bentobox plugin.

**Comment by hetile1** [comment]
Thank you sir! That fixed the issue. 

I'm not exactly sure how the visit addon was installed, I think it was with the initial bundle and we never used it.

I updated to `Visit 1.3.0 (ENABLED)` and it's not crashing anymore.
