### ISSUE TITLE
After 1 restart, OneBlock works, after second it dont work

### ISSUE THREAD

**Issue by AgentPieCZ** [BentoBoxWorld/AOneBlock#177]
#### Describe the bug
After 1 restart OneBlock works, after second no, its 50/50 it will work.

#### Steps to reproduce the behavior
Simple restart of server cause it, but not every time, im confused

##### Output of `/bbox version` (Mandatory)

```
Paper 1.16.5
Bentobox 1.16.2
Database JSON
Loaded game worlds:
Loaded Addons:
AOneBlock 1.7.0 ERROR
Biomes 1.7.0 DISABLED
Chat 1.1.3 Enabled
Likes 2.1.1 Enabled
Limits 1.15.5 Enabled
TwerkingForTress 1.4.1 Enabled
Warps 1.10.2 Disabled
```

#### Plugins (Optional)

```
Plugins (44): AdvancedBan*, ArmorStandEditor, AsyncWorldEdit, AuctionMaster, AutoMessage*, AutoPluginLoader, BentoBox, BossShopPro, ChatControl, ChestShop, Citizens, ClearLag, CommandWhitelist, CoreProtect, CustomHeads*, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, GoldenCrates, Harbor, HolographicDisplays, InventoryRollback, Jobs, LuckPerms, MiniaturePets, MMOItems, MMOLib, Multiverse-Core, NexEngine, OptEco, PlaceholderAPI, ProtocolLib, SilkSpawners, SkinsRestorer, Spartan, TAB, ThirdCurrency*, TradeSystem, Vault, ViaVersion, WorldEdit, WorldGuard, WorldGuardExtraFlags
```
 
### Additional context (Optional)

Error after /ob after restart:
```
Console11:40:47
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1983) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1936) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-579]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-579]
at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
at world.bentobox.bentobox.paperlib.features.chunkisgenerated.ChunkIsGeneratedApiExists.isChunkGenerated(ChunkIsGeneratedApiExists.java:8) ~[?:?]
at world.bentobox.bentobox.paperlib.environments.Environment.isChunkGenerated(Environment.java:105) ~[?:?]
at world.bentobox.bentobox.paperlib.PaperLib.isChunkGenerated(PaperLib.java:180) ~[?:?]
at world.bentobox.bentobox.util.Util.isChunkGenerated(Util.java:460) ~[?:?]
at world.bentobox.bentobox.util.Util.isChunkGenerated(Util.java:449) ~[?:?]
at world.bentobox.bentobox.managers.island.DefaultNewIslandLocationStrategy.isIsland(DefaultNewIslandLocationStrategy.java:96) ~[?:?]
at world.bentobox.bentobox.managers.island.DefaultNewIslandLocationStrategy.getNextLocation(DefaultNewIslandLocationStrategy.java:49) ~[?:?]
at world.bentobox.bentobox.managers.island.NewIsland.makeNextIsland(NewIsland.java:277) ~[?:?]
at world.bentobox.bentobox.managers.island.NewIsland.newIsland(NewIsland.java:175) ~[?:?]
at world.bentobox.bentobox.managers.island.NewIsland.<init>(NewIsland.java:62) ~[?:?]
at world.bentobox.bentobox.managers.island.NewIsland$Builder.build(NewIsland.java:159) ~[?:?]
at world.bentobox.bentobox.api.commands.island.IslandCreateCommand.makeIsland(IslandCreateCommand.java:96) ~[?:?]
at world.bentobox.bentobox.api.commands.island.IslandCreateCommand.execute(IslandCreateCommand.java:84) ~[?:?]
at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[?:?]
at world.bentobox.bentobox.api.commands.island.DefaultPlayerCommand.lambda$runCommand$0(DefaultPlayerCommand.java:116) ~[?:?]
at java.util.Optional.map(Optional.java:265) ~[?:?]
at world.bentobox.bentobox.api.commands.island.DefaultPlayerCommand.runCommand(DefaultPlayerCommand.java:116) ~[?:?]
at world.bentobox.bentobox.api.commands.island.DefaultPlayerCommand.execute(DefaultPlayerCommand.java:105) ~[?:?]
at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[?:?]
at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-579]
... 18 more
```

**Comment by BONNe** [comment]
Are you sure it is the first error message?


As by the status of Addon and the status of Biomes, it looks like there is an issue at the server startup, that is not in this error log.

**Comment by AgentPieCZ** [comment]
Found this one on startup
[09:40:35] [Server thread/INFO]: [BentoBox] Enabling game mode addons...
[09:40:35] [Server thread/INFO]: [BentoBox] Enabling AOneBlock (1.7.0)...
[09:40:35] [Server thread/INFO]: [BentoBox] [AOneBlock] Creating AOneBlock world ...
[09:40:35] [Craft Scheduler Thread - 22/INFO]: [GoldenCrates] Auto-save: Saved 0 online users | 0 offline users.
[09:40:35] [Craft Scheduler Thread - 5/INFO]: [MMOLib] A new build is available: 1.0.14.1 (you are running 1.7.1)
[09:40:35] [Craft Scheduler Thread - 5/INFO]: [MMOLib] Download it here: https://www.spigotmc.org/resources/73855/
[09:40:35] [Server thread/INFO]: World oneblock_world is a duplicate of another world and has been prevented from loading. Please delete the uid.dat file from oneblock_world's world directory if you want to be able to load the duplicate world.
[09:40:35] [Server thread/ERROR]: [BentoBox] Skipping AOneBlock due to an unhandled exception...
[09:40:35] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException: Gamemode overworld object is null for AOneBlock
	at world.bentobox.bentobox.managers.IslandWorldManager.addGameMode(IslandWorldManager.java:152)
	at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:229)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:177)
	at world.bentobox.bentobox.BentoBox.completeSetup(BentoBox.java:186)
	at world.bentobox.bentobox.BentoBox.lambda$onEnable$0(BentoBox.java:172)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1064)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
	at java.base/java.lang.Thread.run(Thread.java:829)

[09:40:35] [Server thread/INFO]: [BentoBox] Enabling other addons...
[09:40:35] [Server thread/INFO]: [BentoBox] Enabling TwerkingForTrees (1.4.1)...
[09:40:35] [Server thread/INFO]: [BentoBox] Enabling Biomes (1.7.0)...
[09:40:35] [Server thread/ERROR]: [BentoBox] [Biomes] Biomes could not hook into any GameMode so will not do anything!
[09:40:35] [Server thread/INFO]: [BentoBox] Biomes is disabled.
[09:40:35] [Server thread/INFO]: [BentoBox] Enabling Likes (2.1.1)...
[09:40:35] [Craft Scheduler Thread - 21/INFO]: Detected new update (2.1.3b), download at https://www.spigotmc.org/resources/76179
[09:40:35] [Server thread/INFO]: [BentoBox] Loading likes...

**Comment by AgentPieCZ** [comment]
-> World oneblock_world is a duplicate of another world and has been prevented from loading. Please delete the uid.dat file from oneblock_world's world directory if you want to be able to load the duplicate world.
[09:40:35] [Server thread/ERROR]: [BentoBox] Skipping AOneBlock due to an unhandled exception...  <- what?... there is only 1 one block world and 1 one block nether world, what created plugin alone

**Comment by BONNe** [comment]
Do AOneBlock world is set as the default world in server.properties?

**Comment by AgentPieCZ** [comment]
its not default world, its world what created one block addon , multiverse is unused now

**Comment by BONNe** [comment]
Ok, then there is one more possibility...
Do you have multiple AOneblock addon instances in `/plugins/bentobox/addons` folder?

**Comment by AgentPieCZ** [comment]
no, there is only one

**Comment by BONNe** [comment]
Do you have something in `bukkit.yml` under `worlds` section?

It may not contain `worlds` if it is not added. 
And what is the name of your default world?

**Comment by AgentPieCZ** [comment]
in bukkit.yml ?
' settings:
  allow-end: false
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: -1
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server se restartuje
  minimum-api: none
spawn-limits:
  monsters: 70
  animals: 10
  water-animals: 15
  water-ambient: 20
  ambient: 15
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  water-spawns: 1
  water-ambient-spawns: 1
  ambient-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml '

**Comment by AgentPieCZ** [comment]
in paper.yml i didnt find anything, what could block from creating or loading world

**Comment by AgentPieCZ** [comment]
in bukkit.yml i didnt find "worlds" section, default name of world is world -> one block world is oneblock_world

**Comment by BONNe** [comment]
That is very weird that something else is creating or loading the oneblock world. 
If that is not Bukkit, then it could Multiverse. 

Well, you can try to add this at the end in bukkit.yml:
```
worlds:
  oneblock_world:
    generator: BentoBox
  oneblock_world_nether:
    generator: BentoBox
  oneblock_world_the_end:
    generator: BentoBox
```

**Comment by AgentPieCZ** [comment]
found in multiverse :  

 oneblock_world:
    ==: MVWorld
    hidden: 'false'
    alias: oneblock_world
    color: WHITE
    style: NORMAL
    pvp: 'false'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings ...

**Comment by AgentPieCZ** [comment]
> That is very weird that something else is creating or loading the oneblock world.
> If that is not Bukkit, then it could Multiverse.
> 
> Well, you can try to add this at the end in bukkit.yml:
> 
> ```
> worlds:
>   oneblock_world:
>     generator: BentoBox
>   oneblock_world_nether:
>     generator: BentoBox
>   oneblock_world_the_end:
>     generator: BentoBox
> ```

Trying this now, restarting server several times

**Comment by AgentPieCZ** [comment]
> That is very weird that something else is creating or loading the oneblock world.
> If that is not Bukkit, then it could Multiverse.
> 
> Well, you can try to add this at the end in bukkit.yml:
> 
> ```
> worlds:
>   oneblock_world:
>     generator: BentoBox
>   oneblock_world_nether:
>     generator: BentoBox
>   oneblock_world_the_end:
>     generator: BentoBox
> ```

looks like this one worked, only, i didnt used oneblock_world_the_end , bcs that world doesnt exist

**Comment by BONNe** [comment]
So it means MultiVerse was enabled before BentoBox and loaded the world. That is weird, as BentoBox should load before.
