### ISSUE TITLE
Issue with holograms

### ISSUE THREAD

**Issue by Jcodeerd** [BentoBoxWorld/AOneBlock#204]
### Expected behavior

That the hologram doesnt break when rebooting the serve

### Observed/Actual behavior

![unknown](https://user-images.githubusercontent.com/68161666/134722841-b35e4cf3-f30c-4437-b55e-1203b1c4008b.png)
This happens after a reboot, and before the reboot the colora were fine. (Yes i used the & character)

### Steps/models to reproduce

Create an island
Reboot server

### BentoBox version

[20:28:59] [Server thread/INFO]: Running AIRPLANE 1.17.1. [20:28:59] [Server thread/INFO]: BentoBox version: 1.17.2 
[20:28:59] [Server thread/INFO]: Database: JSON [20:28:59] [Server thread/INFO]: Loaded Game Worlds: 
[20:28:59] [Server thread/INFO]: oneblock_ world (OneBlock): Overworld, Nether* 
[20:28:59] [Server thread/INFO]: Loaded Addons: [20:28:59] [Server thread/INFO]: AOneBlock 1.8.1 (ENABLED) 
[20:28:59] [Server thread/INFO]: Border 3.2.0 (ENABLED) 
[20:28:59] [Server thread/INFO]: ControlPanel 1.13.0 (ENABLED) 
[20:28:59] [Server thread/INFO]: Level 2.7.2 (ENABLED) 
[20:28:59] [Server thread/INFO]: Visit 1.4.0 (ENABLED) 
[20:28:59] [Server thread/INFO]: Warps 1.11.1 (ENABLED)

### Plugin list

Plugins (46): AdvancedBan, ajStartCommands*, AntiAFK*, BentoBox, BuycraftX, Citizens, ClicksPerSecond*, CommandCooldown, CoreProtect, CrateReloaded, DeluxeTags, DiscordSRV, EconomyShopGUI, EpicGuard*, Essentials, EssentialsChat, EssentialsSpawn, GCore, Harbor, HeadDB, HolographicDisplays, InteractiveChat, LPC, LuckPerms, MyCommand, NexEngine, NoCheatPlus, PlaceholderAPI, PlugMan, ProtocolLib, QuickShop, Scoreboard-revision*, SilkSpawners, spark, StaffChat, TabList, TempFly, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, VirtualTag, WorldBorderAPI, WorldEdit, WorldGuard

**Comment by Jcodeerd** [comment]
![image](https://user-images.githubusercontent.com/68161666/134768538-9bfc772e-aa51-4fda-ada8-bc0c82524cf6.png)
it changes in the files too, but idk what the cause is

**Comment by tastybento** [comment]
@Jcodeerd What OS are you using? Windows? What language is your system in? It looks like your system cannot store UTF-8 characters so they just become ?'s (the color code § should be able to be stored)...

**Comment by tastybento** [comment]
I made a change to store the hologram text in a different way in the database. Try the snapshot version from https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/. You will need to start a new island to make a new database entry to see if anything changes. Let me know if it works.

**Comment by Jcodeerd** [comment]
> @Jcodeerd What OS are you using? Windows? What language is your system in? It looks like your system cannot store UTF-8 characters so they just become ?'s (the color code § should be able to be stored)...

My host uses Linux, 64bit. Im assuming en-us / en-gb

I'll try the dev build

**Comment by Jcodeerd** [comment]
`[18:29:11 ERROR]: Could not pass event BlockBreakEvent to BentoBox v1.17.2
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringEscapeUtils
        at world.bentobox.aoneblock.dataobjects.OneBlockIslands.setHologram(OneBlockIslands.java:89) ~[AOneBlock-1.9.0-SNAPSHOT-b219.jar:?]
        at world.bentobox.aoneblock.listeners.HoloListener.process(HoloListener.java:78) ~[AOneBlock-1.9.0-SNAPSHOT-b219.jar:?]
        at world.bentobox.aoneblock.listeners.BlockListener.process(BlockListener.java:330) ~[AOneBlock-1.9.0-SNAPSHOT-b219.jar:?]
        at world.bentobox.aoneblock.listeners.BlockListener.lambda$onBlockBreak$3(BlockListener.java:248) ~[AOneBlock-1.9.0-SNAPSHOT-b219.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at world.bentobox.aoneblock.listeners.BlockListener.onBlockBreak(BlockListener.java:248) ~[AOneBlock-1.9.0-SNAPSHOT-b219.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor654.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-79]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-79]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-79]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:356) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:240) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1734) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Airplane-79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-79]
        at java.lang.Thread.run(Thread.java:831) [?:?]`
        
        
that didnt work :(

**Comment by tastybento** [comment]
No, it's not that. Let me try and fix.

**Comment by Jcodeerd** [comment]
Awesome!

**Comment by Jcodeerd** [comment]
`[18:33:52 WARN]: [BentoBox] Task #780 for BentoBox v1.17.2 generated an exception
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringEscapeUtils
        at world.bentobox.aoneblock.dataobjects.OneBlockIslands.getHologram(OneBlockIslands.java:82) ~[AOneBlock-1.9.0-SNAPSHOT-b219.jar:?]
        at world.bentobox.aoneblock.AOneBlock.allLoaded(AOneBlock.java:251) ~[AOneBlock-1.9.0-SNAPSHOT-b219.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at world.bentobox.bentobox.managers.AddonsManager.allLoaded(AddonsManager.java:649) ~[BentoBox-1.17.2.jar:?]
        at world.bentobox.bentobox.BentoBox.lambda$completeSetup$2(BentoBox.java:249) ~[BentoBox-1.17.2.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-87]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringEscapeUtils
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:148) ~[patched_1.17.1.jar:git-Airplane-87]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Airplane-87]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 13 more`
        
im not sure whether this helps, but this happens at booting the server

**Comment by tastybento** [comment]
It's the same error `StringEscapeUtils` isn't included. Give me a few mins to sort this out.

**Comment by Jcodeerd** [comment]
Yeah sure, take your time :) I wont be here for a few hours so its fine

**Comment by tastybento** [comment]
Okay, try now https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/ and see if that fixes the issue. I'm still not happy that your system cannot save the unicode chars for some reason. That seems odd.

**Comment by tastybento** [comment]
@Jcodeerd Any luck?

**Comment by Jcodeerd** [comment]
yeah, it works fine now, but it still gives an error:



`[09:43:47 ERROR]: Could not pass event BlockSpreadEvent to BentoBox v1.17.2
java.lang.ClassCastException: class java.lang.String cannot be cast to
class java.lang.Boolean (java.lang.String and java.lang.Boolean are in
module java.base of loader 'bootstrap')
        at
world.bentobox.bentobox.api.flags.Flag.isSetForWorld(Flag.java:189)
~[BentoBox-1.17.2.jar:?]
        at
world.bentobox.bentobox.listeners.flags.worldsettings.TreesGrowingOutsideRangeListener.onChorusGrow(TreesGrowingOutsideRangeListener.java:40)
~[BentoBox-1.17.2.jar:?]
        at
com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown
Source) ~[?:?]
        at
org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
~[patched_1.17.1.jar:git-Airplane-87]
        at
co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
~[patched_1.17.1.jar:git-Airplane-87]
        at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
~[patched_1.17.1.jar:git-Airplane-87]
        at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
~[patched_1.17.1.jar:git-Airplane-87]
        at
org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:845)
~[patched_1.17.1.jar:git-Airplane-87]
        at
org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleBlockSpreadEvent(CraftEventFactory.java:831)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.world.level.block.BlockDirtSnowSpreadable.tick(BlockDirtSnowSpreadable.java:61)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.world.level.block.state.BlockBase$BlockData.b(BlockBase.java:921)
~[patched_1.17.1.jar:git-Airplane-87]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:950)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.server.level.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1049)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.server.level.ChunkProviderServer.tick(ChunkProviderServer.java:934)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.server.level.WorldServer.doTick(WorldServer.java:731)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
~[patched_1.17.1.jar:git-Airplane-87]
        at
net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
~[patched_1.17.1.jar:git-Airplane-87]
        at java.lang.Thread.run(Thread.java:831) [?:?]`

Op ma 27 sep. 2021 om 01:20 schreef tastybento ***@***.***>:

**Comment by Jcodeerd** [comment]
that worked, but now this is messed up 😅  ![image](https://user-images.githubusercontent.com/68161666/135484938-9397de0b-2d0a-4cb0-bc37-9bbe4ce29d29.png)

**Comment by tastybento** [comment]
As I thought, the issue is that your file system, or operating system is not handling UTF-8 (Unicode) for some reason. This is kind of out of scope here and I'm not sure why it'd be an issue for you, sorry. I recommend you install a server on your own PC, (use, say Paper) as a test and run it and I think you'll find it will work.

**Comment by Jcodeerd** [comment]
Oki, ill check that with the host than. Thanks for all of your help!!
