### ISSUE TITLE
Request for Jets minions

### ISSUE THREAD

**Issue by Verzante** [BentoBoxWorld/AOneBlock#300]
### Is your feature request related to a problem?

Its half a bug / half a request, I will explain. I have installed Jets Minions on my oneblock server. Everything works great, but if the minion mines the last magic block in the phase, the island level goes up but the magic block disappears and needs to be re-mined by player. For the best explanation, here is a video: https://imgur.com/a/zeOXrMw 

### Describe the solution you'd like.

The solution would be just to implement it, so when the minion mines the last block, the magic book wouldn't disappear to let the minion continue mining

### Describe alternatives you've considered.

No alternatives. I have already talked about this on your discord support and I was told to make a github request for it.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
This is more a bug. What is the output of `/bbox version`?
Does it work if `drop-on-top:` in config.yml is set to false? Unfortunately, I don't have the latest version of jets minions, so I cannot test it right now.

**Comment by Verzante** [comment]
> This is more a bug. What is the output of `/bbox version`? Does it work if `drop-on-top:` in config.yml is set to false? Unfortunately, I don't have the latest version of jets minions, so I cannot test it right now.
Output of /bbox version:
![Minecraft) 13 02 2023 8_40_15](https://user-images.githubusercontent.com/81901320/218398820-acfb97b2-0bb7-466c-9ff7-05d8b198a6f1.png)

And no, it does not work either if drop-on-top is set to false

**Comment by Verzante** [comment]
Any progress on this? Not pressuring, just want to make sure its not forgotten

**Comment by tastybento** [comment]
I don't have Jets Minions. Sorry. If you can share yours for this debugging only then send it to tastybento @ bentobox.world

**Comment by Verzante** [comment]
> tastybento @ bentobox.world

I have sent you the email with the jar

**Comment by Verzante** [comment]
> I don't have Jets Minions. Sorry. If you can share yours for this debugging only then send it to tastybento @ bentobox.world

Hmm, the mail was not sent because of copyright issues. Do you have discord?

**Comment by tastybento** [comment]
Weird. You can try and zip it. But yes, I do have Discord - tastybento#6141

**Comment by tastybento** [comment]
@Verzante 

The plugin for minions says: The minion cannot perform his actions here (is the minion in a suitable area?)

I know you asked this on Discord - how do you get past this?

**Comment by tastybento** [comment]
Error when last block is mined:
```
[12:02:28 ERROR]: Could not pass event EntityInteractEvent to BentoBox v1.22.1-SNAPSHOT-LOCAL
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player" is null
	at world.bentobox.bentobox.api.user.User.getInstance(User.java:107) ~[BentoBox-1.22.1-SNAPSHOT-LOCAL.jar:?]
	at world.bentobox.aoneblock.listeners.BlockListener.lambda$checkPhase$16(BlockListener.java:496) ~[AOneBlock-1.12.2-SNAPSHOT-LOCAL.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at world.bentobox.aoneblock.listeners.BlockListener.checkPhase(BlockListener.java:494) ~[AOneBlock-1.12.2-SNAPSHOT-LOCAL.jar:?]
	at world.bentobox.aoneblock.listeners.BlockListener.process(BlockListener.java:349) ~[AOneBlock-1.12.2-SNAPSHOT-LOCAL.jar:?]
	at world.bentobox.aoneblock.listeners.BlockListener.lambda$onBlockBreakByMinion$4(BlockListener.java:247) ~[AOneBlock-1.12.2-SNAPSHOT-LOCAL.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at world.bentobox.aoneblock.listeners.BlockListener.onBlockBreakByMinion(BlockListener.java:247) ~[AOneBlock-1.12.2-SNAPSHOT-LOCAL.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor472.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-399]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at me.jet315.minions.minions.types.MinerMinion.performAction(MinerMinion.java:168) ~[JetsMinions-7.7.3.jar:?]
	at me.jet315.minions.manager.MinionTask$1.run(MinionTask.java:39) ~[JetsMinions-7.7.3.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-399]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-399]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-399]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-399]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by tastybento** [comment]
The issue is the commands may be run at the end and start of a phase, and if an NPC is doing the breaking, then it needs to fall back to the owner (if they are online).

**Comment by tastybento** [comment]
Okay, fixed! Should be available on the [CI in a few mins](https://ci.codemc.io/job/BentoBoxWorld/job/AOneBlock/).
