### ISSUE TITLE
Bug in phases of aoneblock

### ISSUE THREAD

**Issue by Talavera18** [BentoBoxWorld/AOneBlock#337]
### Expected behavior

a menu for choice an phase

### Observed/Actual behavior

![image](https://github.com/BentoBoxWorld/AOneBlock/assets/99893223/041499d5-9487-4082-b342-62c6e17fb609)

### Steps/models to reproduce

https://pastebin.com/9YvmzNQ1
```
[22:39:26] [Server thread/INFO]: Ta1avera issued server command: /isla fases
[22:39:26] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'isla fases' in world.bentobox.aoneblock.commands.island.PlayerCommand(isla)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1003) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[pufferfish-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2300) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2260) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-15]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Biome.name()" because "biome" is null
	at world.bentobox.bentobox.hooks.LangUtilsHook.getBiomeName(LangUtilsHook.java:198) ~[BentoBox-1.24.1.jar:?]
	at world.bentobox.aoneblock.panels.PhasesPanel.createPhaseButton(PhasesPanel.java:410) ~[AOneBlock-1.14.1.jar:?]
	at world.bentobox.aoneblock.panels.PhasesPanel.createPhaseButton(PhasesPanel.java:317) ~[AOneBlock-1.14.1.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.makeAddonButton(TemplatedPanel.java:396) ~[BentoBox-1.24.1.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.makeButton(TemplatedPanel.java:340) ~[BentoBox-1.24.1.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.processItemData(TemplatedPanel.java:108) ~[BentoBox-1.24.1.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.populateInventoryPanel(TemplatedPanel.java:90) ~[BentoBox-1.24.1.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.generatePanel(TemplatedPanel.java:69) ~[BentoBox-1.24.1.jar:?]
	at world.bentobox.bentobox.api.panels.TemplatedPanel.<init>(TemplatedPanel.java:57) ~[BentoBox-1.24.1.jar:?]
	at world.bentobox.bentobox.api.panels.builders.TemplatedPanelBuilder.build(TemplatedPanelBuilder.java:150) ~[BentoBox-1.24.1.jar:?]
	at world.bentobox.aoneblock.panels.PhasesPanel.build(PhasesPanel.java:124) ~[AOneBlock-1.14.1.jar:?]
	at world.bentobox.aoneblock.panels.PhasesPanel.openPanel(PhasesPanel.java:588) ~[AOneBlock-1.14.1.jar:?]
	at world.bentobox.aoneblock.commands.island.IslandPhasesCommand.execute(IslandPhasesCommand.java:30) ~[AOneBlock-1.14.1.jar:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:284) ~[BentoBox-1.24.1.jar:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:251) ~[BentoBox-1.24.1.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 22 more
```

### BentoBox version

1.24.1

### Plugin list

[22:47:18] [Server thread/INFO]: Server Plugins (58):
[22:47:18] [Server thread/INFO]: Paper Plugins:
[22:47:18] [Server thread/INFO]:  - EconomyShopGUI
[22:47:18] [Server thread/INFO]: Bukkit Plugins:
[22:47:18] [Server thread/INFO]:  - ajLeaderboards, AureliumSkills, BentoBox, BentoBox-AOneBlock, BentoBox-Bank, BentoBox-Biomes, BentoBox-Challenges, BentoBox-Level, BentoBox-Likes, BentoBox-Visit
[22:47:18] [Server thread/INFO]:  BentoBox-Warps, BungeeGuard, Citizens, CMILib, CommandPanels, ConditionalEvents, CoreProtect, DailyRewardsPlus, DecentHolograms, DeluxeMenus
[22:47:18] [Server thread/INFO]:  Essentials, EssentialsSpawn, EvenMoreFish, ExcellentCrates, FastAsyncWorldEdit, Hyperverse, JetsMinions, Jobs, LeatherColorizer, LPC
[22:47:18] [Server thread/INFO]:  LuckPerms, MinePickaxe, MyCommand, NexEngine, PinataParty, PlaceholderAPI, PlayerBounties, PlayerKits, PlayerWarps, PrisonRanksX
[22:47:18] [Server thread/INFO]:  ProtocolLib, Quests, SilkSpawners, spark, TAB, TempFly, TimberCore, Vault, ViaBackwards, ViaVersion
[22:47:18] [Server thread/INFO]:  VoidGen, Votifier, Vulcan, WorldBorderAPI, WorldGuard, WorldGuardEvents, zAuctionHouseV3

**Comment by Talavera18** [comment]
Phases

[phases.tar.gz](https://github.com/BentoBoxWorld/AOneBlock/files/12340071/phases.tar.gz)

**Comment by tastybento** [comment]
I added code to prevent the error, but it was caused by the file `10000_plenty_chests.yml` having `8500:` in it at the start instead of `10000:`. This caused a blank phase to be created at 8500 blocks with no name, biome, or icon, etc. Once I changed the file to 10000, then it worked. But I also fixed the code so that it will not cause an error next time.
