### ISSUE TITLE
could not pass breakblockevent to bentobox // Could not pass event PlayerInteractEvent to BentoBox v1.24.1

### ISSUE THREAD

**Issue by puwuld** [BentoBoxWorld/AOneBlock#342]
### Expected behavior

nothing

### Observed/Actual behavior

error with breakblockevent and playerineractevent

### Steps/models to reproduce

I broke a block and place it back and it show those errors.

### BentoBox version

Running PAPER 1.19.4.
BentoBox version: 1.24.1
Database: JSON
Loaded Game Worlds:
oneblock_world (OneBlock): Overworld, Nether*, The End*
Loaded Addons:
AOneBlock 1.14.2 (ENABLED)
Bank 1.7.0 (ENABLED)
Biomes 2.1.1 (ENABLED)
Challenges 1.2.0 (ENABLED)
Chat 1.1.4 (ENABLED)
CheckMeOut 1.1.1 (ENABLED)
ControlPanel 1.13.0 (ENABLED)
Level 2.11.0 (ENABLED)
Likes 2.3.1 (ENABLED)
Limits 1.19.1 (ENABLED)
Warps 1.13.0 (ENABLED)

### Plugin list

Bukkit Plugins:
 - AdvancedBan, BentoBox, BentoBox-AOneBlock, BentoBox-Bank, BentoBox-Biomes, BentoBox-Challenges, BentoBox-CheckMeOut, BentoBox-Level, BentoBox-Likes, BentoBox-Limits
 
### Other

Errors:

- [Fri 23:15:42 ERROR Minecraft] Could not pass event BlockBreakEvent to BentoBox v1.24.1
java.lang.NoClassDefFoundError: org/bukkit/block/BrushableBlock
    at BentoBox-1.24.1.jar//world.bentobox.bentobox.listeners.flags.protection.BlockInteractionListener.checkSpecialCases(BlockInteractionListener.java:245)
    at BentoBox-1.24.1.jar//world.bentobox.bentobox.listeners.flags.protection.BlockInteractionListener.checkClickedBlock(BlockInteractionListener.java:94)
    at BentoBox-1.24.1.jar//world.bentobox.bentobox.listeners.flags.protection.BlockInteractionListener.onBlockBreak(BlockInteractionListener.java:264)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor714.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:377)
    at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:336)
    at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:214)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1871)
    at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42)
    at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15)
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51)
    
    - [Fri 23:16:41 ERROR Minecraft] Could not pass event PlayerInteractEvent to BentoBox v1.24.1
java.lang.NoClassDefFoundError: org/bukkit/block/BrushableBlock
    at BentoBox-1.24.1.jar//world.bentobox.bentobox.listeners.flags.protection.BlockInteractionListener.checkSpecialCases(BlockInteractionListener.java:245)
    at BentoBox-1.24.1.jar//world.bentobox.bentobox.listeners.flags.protection.BlockInteractionListener.checkClickedBlock(BlockInteractionListener.java:94)
    at BentoBox-1.24.1.jar//world.bentobox.bentobox.listeners.flags.protection.BlockInteractionListener.onPlayerInteract(BlockInteractionListener.java:48)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor713.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
    at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:564)
    at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1959)
    at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37)
    at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9)
    at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51)
    at net.minecraft.server.TickTask.run(TickTask.java:18)
    at net.minecraft.util.thread.BlockableEventL

**Comment by BONNe** [comment]
BentoBox 1.24+ is for Minecraft 1.20.1

Please, use https://download.bentobox.world/custom and select 1.19 or update server to 1.20.1
