### ISSUE TITLE
Magicblock not appear - Bug error in console 1.15.2

### ISSUE THREAD

**Issue by Zetthh** [BentoBoxWorld/AOneBlock#92]
#### Describe the bug
my players when finish phases go to 0 blocks but when break magicblock this not appear.

have last fix, 11000_goto_0.yml.

'11000':
  gotoBlock: 0

#### Error in console.

`[00:03:49] [Server thread/INFO]: Zetth_ issued server command: /obadmin why gafyavfyua
[00:03:53] [Async Chat Thread - #0/INFO]: * [Usuario] Zetth_ ≫ minalo
[00:03:55] [Server thread/INFO]: [BentoBox] Why: BlockBreakEvent in world oneblock_world at 7200,80,8800
[00:03:55] [Server thread/INFO]: [BentoBox] Why: gafyavfyua BREAK_BLOCKS - RANK_ALLOWED
[00:03:55] [Server thread/ERROR]: Could not pass event BlockBreakEvent to BentoBox v1.13.1
java.lang.NullPointerException: null
	at world.bentobox.aoneblock.listeners.BlockListener.process(BlockListener.java:231) ~[?:?]
	at world.bentobox.aoneblock.listeners.BlockListener.lambda$onBlockBreak$2(BlockListener.java:199) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_252]
	at world.bentobox.aoneblock.listeners.BlockListener.onBlockBreak(BlockListener.java:199) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor546.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-354]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-354]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-354]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:321) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:280) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:246) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1360) ~[?:git-Paper-354]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-354]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-354]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[00:03:56] [Server thread/INFO]: [BentoBox] Why: EntityPickupItemEvent in world oneblock_world at 7200,80,8800
[00:03:56] [Server thread/INFO]: [BentoBox] Why: gafyavfyua ITEM_PICKUP - RANK_ALLOWED`

##### Output of `/bbox version` (Mandatory)
PAPER 1.15.2
BENTOBOX 1.13.1
AONEBLOCK 1.3.3
```

**Comment by victoryneM** [comment]
I had the same bug tonight, I had to copy paste the island on another one as the magic block was disapeared :(
